/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'state' : string,
  'phone' : string,
}
export interface OrderItem {
  'size' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderType {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'shippingCountry' : string,
  'createdAt' : bigint,
  'shippingZip' : string,
  'shippingStreet' : string,
  'shippingCity' : string,
  'totalAmount' : bigint,
  'stripePaymentIntentId' : string,
  'items' : Array<OrderItem>,
  'orderNumber' : bigint,
  'orderNotes' : string,
  'customerEmail' : string,
  'shippingState' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[OrderType], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllOrders' : ActorMethod<[], Array<OrderType>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], [] | [OrderType]>,
  'getOrdersByEmail' : ActorMethod<[string], Array<OrderType>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];